
spring.datasource.url=jdbc:postgresql://localhost:5432/myapp
spring.datasource.username=postgres
spring.datasource.password=xristina123


spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always
spring.sql.init.platform=postgresql


app.jwt.secret=xristinaSecretKey123456789012345678901234
app.jwt.expiration=86400000


spring.application.name=job-search-backend