spring.datasource.url=jdbc:postgresql://db:5432/myapp
spring.datasource.username=postgres
spring.datasource.password=xristina123
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
